SET SERVEROUTPUT ON;

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE CUSTOMERS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE CUSTOMERS (
    CustomerID NUMBER PRIMARY KEY,
    Age NUMBER,
    Balance NUMBER,
    IsVIP VARCHAR2(5)
);

INSERT INTO CUSTOMERS VALUES (1, 35, 15000, 'FALSE');
INSERT INTO CUSTOMERS VALUES (2, 50, 9500, 'FALSE');
INSERT INTO CUSTOMERS VALUES (3, 60, 12000, 'FALSE');

COMMIT;

-- PL/SQL Block: Set VIP flag for balance > 10000
BEGIN
    DBMS_OUTPUT.PUT_LINE('--- VIP Status Grant for Balance > 10000 ---');
    FOR rec IN (
        SELECT CustomerID FROM CUSTOMERS WHERE Balance > 10000
    ) LOOP
        UPDATE CUSTOMERS
        SET IsVIP = 'TRUE'
        WHERE CustomerID = rec.CustomerID;

        DBMS_OUTPUT.PUT_LINE('VIP granted to Customer ID: ' || rec.CustomerID);
    END LOOP;
END;
/
